### ISSUE TITLE
Getting 'false' returned for getCurrentUser()

### ISSUE THREAD

**Issue by Gremlyn** [benja-M-1/wordpress-sdk#1]
Running getUsers() works fine, but running getCurrentUser returns 'false'.

If I may suggest an alternate method, you could use wp.getProfile, which gets the details for the current user.

**Comment by benja-M-1** [comment]
Interesting! I will try this. Furthermore, depending on your permissions, an exception could be thrown telling the user that he is now allowed to access the user list.

**Comment by Gremlyn** [comment]
I think not having permissions for accessing the user list was actually the problem I encountered when looking into it a little more in depth. That doesn't seem to be an issue with getProfile, however.

**Comment by benja-M-1** [comment]
I didn't meant that :) Actually I think your solution will solve my issue.

**Comment by benja-M-1** [comment]
@Gremlyn  I did what you suggested me. Tanks!
